name: publish

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shared-goals/text-forge@v1
        with:
          mkdocs_config: mkdocs.yml
          docs_dir: text/ru
          site_dir: public/ru
          cover_image: epub/cover.jpg

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - uses: actions/deploy-pages@v4
